# Codecov configuration for IFPA SDK
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Target coverage for the entire project
        target: 80%
        threshold: 5%
        base: auto
        # Only post status if coverage changes
        informational: false
        # Require coverage check to pass
        if_ci_failed: error

    patch:
      default:
        # Target coverage for new code in patches
        target: 80%
        threshold: 5%
        base: auto
        # Fail if new code doesn't meet coverage requirements
        informational: false
        if_ci_failed: error

    changes:
      default:
        # Track coverage changes
        base: auto
        # Allow minor decreases
        threshold: 2%

  # Ignore patterns
  ignore:
    - "tests/**"
    - "**/__init__.py"
    - "**/__main__.py"
    - "**/test_*.py"

# Comment configuration for pull requests
comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  # Show coverage changes in PR comments
  show_carryforward_flags: false

# GitHub Checks configuration
github_checks:
  annotations: true

# Flags for different test types
flags:
  unittests:
    paths:
      - src/
    carryforward: true

# Ignore file paths
ignore:
  - "docs/**"
  - "scripts/**"
  - "**/*.md"
  - ".github/**"

# Parsing configuration
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

# Slack notifications (optional - configure in Codecov web UI)
slack_app: false
